---
title: "Session 1"
author: "Stevie Pederson"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

The first session for the day is a very basic introduction to R. 
From there we'll start to dig deeper.

### Data Files

We'll discuss during our very first session but we'll need to create a directory on our computer before we start.
We should name this `R_Training` and whatever your OS version of `Documents` is might be a good place for it.
Inside that directory, please create a new directory called data and the following files can be placed in this folder

- [toothData.csv](data/toothData.csv).
- [RealTimeData.xlsx](data/RealTimeData.xlsx)

### Slides

For most of today, I'll present some slides and ask you to follow some (hopefully) simple instructions.

- The first set of slides are available [here](1.1.1_Introduction.html)
- The second set of slides is [here](1.1.2_DataImport.html) 

If you want to follow along, please open these in a new browser tab/window but it might just be easier to follow mine


