---
title: "Day 1"
author: "Stevie Pederson"
date: "`r format(Sys.Date(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

The first session for the day is a very basic introduction to R. 
From there we'll start to dig deeper.

### Data Files

We'll discuss during our very first session but we'll need to

1. Create a directory on our computer before we start. Whatever your OS version of `Documents` is might be a good place for it
2. Name this `R_Training`
3. Inside that directory, please create a new directory called `data` and place the following files in this folder

- [toothData.csv](data/toothData.csv).
- [RealTimeData.xlsx](data/RealTimeData.xlsx)
- [transport.csv](data/transport.csv)
- [contacts.csv](data/contacts.csv)
- [timeCourse.csv](data/timeCourse.csv)
- [PCR.csv](data/PCR.csv)

These are all very small example files we'll commonly refer to throughout the sessions

## Slides

For most of today, I'll present some slides and ask you to follow some (hopefully) simple instructions.
If you want to follow along, please open these in a new browser tab/window but it might just be easier to follow mine and leave your RStudio session as the main focus

### Session 1

- [Introduction](1.1.1_Introduction.html)
- [Loading Data](1.1.2_DataImport.html) 

### Session 2

- [Spreadsheet-Like Data](1.2.1_TidyingData.html)

### Session 3

- [Data Visualisation](1.3.1_DataVisualisation.html)

### Session 4

- [R Markdown](1.4_RMarkdown.html)
